### ISSUE TITLE
chapter 3: NullPointerException when saving Taco design without ingredients

### ISSUE THREAD

**Issue by grolegor** [habuma/spring-in-action-5-samples#40]
**Steps to reproduce:**
1. go to ch03/tacos-jdbc
2. `mvn spring-boot:run` 
3. localhost:8080
4. click on the link "Design a taco"
5. set taco name: "test-taco-name"
6. click on the button: "Submit your taco"

**Expected result:**
An error appears with the text: "You must choose at least 1 ingredient"

**Actual result:**
Whitelabel Error Page
Logs:
> java.lang.NullPointerException: null
> 	at tacos.data.JdbcTacoRepository.save(JdbcTacoRepository.java:31) ~[classes/:na]
> 	at tacos.data.JdbcTacoRepository$$FastClassBySpringCGLIB$$59d8a28e.invoke(<generated>) ~[classes/:na]
> 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
> 	...

**Root cause:**
Taco.java
```
...
  @Size(min=1, message="You must choose at least 1 ingredient")
  private List<Ingredient> ingredients;
...
```
`ingredients` field has `@Size` validation. But according to documentation for `@Size` validation _null_ is considered valid. If you choose no ingredients then `ingredients` field will be _null_ and it is a valid value.

**Comment by bensgith** [comment]
I had got a similar NullPointerException with ingredients. But I think it throws such exception because jdbc.update() in method saveTacoInfo() didn't update the KeyHolder.

```
private long saveTacoInfo(Taco taco) {
    taco.setCreatedAt(new Date());
    PreparedStatementCreator psc = new PreparedStatementCreatorFactory(
            "insert into Taco (name, createdAt) values (?, ?)",
            Types.VARCHAR, Types.TIMESTAMP
    ).newPreparedStatementCreator(Arrays.asList(taco.getName(), new Timestamp(taco.getCreatedAt().getTime())));

    KeyHolder keyHolder = new GeneratedKeyHolder();
    jdbc.update(psc, keyHolder);

    return keyHolder.getKey().longValue(); //TODO this line of code throws NullPointerException because jdbc update didn't update KeyHolder
}
```

**Comment by Sammygracezhu** [comment]
Try this:

private long saveTacoInfo(Taco taco) {
    taco.setCreatedAt(new Date());
    PreparedStatementCreator psc = new PreparedStatementCreatorFactory(
            "insert into Taco (name, createdAt) values (?, ?)",
            Types.VARCHAR, Types.TIMESTAMP
    ).newPreparedStatementCreator(Arrays.asList(taco.getName(), new
Timestamp(taco.getCreatedAt().getTime())));

    KeyHolder keyHolder = new GeneratedKeyHolder();
    jdbc.update(psc, keyHolder);


    *System.out.println(keyHolder.getKey());  //I guess here it will
print null.*


    return 1L; //TODO this line of code throws NullPointerException
because jdbc update doesn't generated key
}

**Comment by banahene** [comment]
I am having a similar problem and still can't find answers. I'm really confused. When I log the taco object received in the Post Request it is not null and has all the right values. When it is passed to the save function though it seems to pass a null value to the function.

**Comment by LiUzHiAn** [comment]
@ghbenl Hi,

I met the same issue as you post.  I guess it's a bug in Spring. Try to use `SimpleJdbcInsert` as  we coded in `JdbcOrderRepository.java` instead, in my case, it works~

**Comment by knastnt** [comment]
you must set this:
`preparedStatementCreatorFactory.setReturnGeneratedKeys(true);`

**Comment by mananmehta11** [comment]
```
private long saveTacoInfo(Taco taco) {
		taco.setCreatedAt(new Date());
		PreparedStatementCreatorFactory pscf = new PreparedStatementCreatorFactory(
				"Insert into Taco(name, createdAt) values(?,?)", Types.VARCHAR, Types.TIMESTAMP);
		pscf.setReturnGeneratedKeys(Boolean.TRUE);
		PreparedStatementCreator psc = pscf.newPreparedStatementCreator(
				Arrays.asList(taco.getName(), new Timestamp(taco.getCreatedAt().getTime())));
		KeyHolder keyHolder = new GeneratedKeyHolder();
		jdbc.update(psc, keyHolder);
		return keyHolder.getKey().longValue();
	}
```

**Comment by CharlesUESTC** [comment]
> **Steps to reproduce:**
> 
> 1. go to ch03/tacos-jdbc
> 2. `mvn spring-boot:run`
> 3. localhost:8080
> 4. click on the link "Design a taco"
> 5. set taco name: "test-taco-name"
> 6. click on the button: "Submit your taco"
> 
> **Expected result:** An error appears with the text: "You must choose at least 1 ingredient"
> 
> **Actual result:** Whitelabel Error Page Logs:
> 
> > java.lang.NullPointerException: null
> > at tacos.data.JdbcTacoRepository.save(JdbcTacoRepository.java:31) ~[classes/:na]
> > at tacos.data.JdbcTacoRepository$$FastClassBySpringCGLIB$$59d8a28e.invoke() ~[classes/:na]
> > at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
> > ...
> 
> **Root cause:** Taco.java
> 
> ```
> ...
>   @Size(min=1, message="You must choose at least 1 ingredient")
>   private List<Ingredient> ingredients;
> ...
> ```
> 
> `ingredients` field has `@Size` validation. But according to documentation for `@Size` validation _null_ is considered valid. If you choose no ingredients then `ingredients` field will be _null_ and it is a valid value.

Anybody knows how to solve this problem?
