### ISSUE TITLE
Chapter 4 defining users in an In-memory user store with Spring Security 5

### ISSUE THREAD

**Issue by kennico** [habuma/spring-in-action-5-samples#41]
I sign in with the following code similar to listing 4.2
```
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication()
                .withUser("buzz")
                .password("infinity")
                .authorities("ROLE_USER");
    }
```
and get this error in **Spring Security 5**
```
java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:244) ~[spring-security-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:198) ~[spring-security-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$LazyPasswordEncoder.matches(WebSecurityConfigurerAdapter.java:594) ~[spring-security-config-5.1.3.RELEASE.jar:5.1.3.RELEASE]
...
```
The [recommended prefix `{noop}`](https://stackoverflow.com/a/47150363/8706476) of password solved my problem.
> In spring-security-core:5.0.0.RC1, the default PasswordEncoder is built as a DelegatingPasswordEncoder. When you store the users in memory, you are providing the passwords in plain text and when trying to retrieve the encoder from the DelegatingPasswordEncoder to validate the password it can't find one that matches the way in which these passwords were stored.
> ...
> You can also simply prefix {noop} to your passwords in order for the DelegatingPasswordEncoder use the NoOpPasswordEncoder to validate these passwords. 
> ...
> `User.withUsername("user").password("{noop}user").roles("USER").build();`

**Comment by kennico** [comment]
Using an [encoder](https://www.baeldung.com/spring-security-5-default-password-encoder) also fixed this error
```
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        PasswordEncoder encoder = PasswordEncoderFactories.createDelegatingPasswordEncoder();

        auth.inMemoryAuthentication()
                .withUser("buzz")
                .password(encoder.encode("infinity"))
                .authorities("ROLE_USER");
    }
```
